# Generated by Django 3.0.4 on 2020-03-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=253)),
                ('unsafe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000)),
                ('unsafe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=2000)),
                ('unsafe', models.BooleanField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_lookup.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=80)),
                ('unsafe', models.BooleanField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_lookup.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_lookup.Port'),
        ),
    ]
