# Generated by Django 3.0.4 on 2020-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=253, unique=True),
        ),
    ]
