# Generated by Django 3.0.4 on 2020-03-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_lookup', '0002_auto_20200318_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='unsafe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='unsafe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='unsafe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='unsafe',
            field=models.BooleanField(default=True),
        ),
    ]
